### ISSUE TITLE
Additional sources of microhaplotypes

### ISSUE THREAD

**Issue by standage** [bioforensics/MicroHapDB#24]
- [x] Hiroaki et al (https://doi.org/10.1016/j.legalmed.2015.06.003); see #31
- [x] Chen et al (https://doi.org/10.1016/j.fsigen.2019.02.018); see #32
- [x] Voskoboinik et al (https://doi.org/10.1016/j.fsigen.2018.05.001); see #47 
- [x] de la Puente et al (https://doi.org/10.1016/j.fsigen.2019.102213); see #49
